import type {
  ArmeniaSignalDomain,
  ArmeniaSourceDefinition,
  ArmeniaSourceReadiness,
} from '@/types/armenia-signal';

/**
 * Armenia Signal source registry.
 *
 * This registry describes provenance, topical coverage and collection intent.
 * It is not an editorial ranking. Official sources are primary records for
 * their own actions, notices and published datasets; claims about third
 * parties still require attribution and, for material alerts, corroboration.
 *
 * Collection readiness is deliberately separate from source inclusion. A
 * source may be important to the Armenia data model before a dedicated parser
 * or live feed is enabled for it.
 */
export const ARMENIA_SOURCE_REGISTRY: readonly ArmeniaSourceDefinition[] = [
  {
    id: 'gov-am',
    name: 'Government of Armenia',
    aliases: ['ՀՀ կառավարություն'],
    host: 'gov.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['politics', 'economy', 'infrastructure', 'security', 'regional'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'parliament-am',
    name: 'National Assembly of Armenia',
    aliases: ['ՀՀ Ազգային ժողով'],
    host: 'parliament.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['politics'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'president-am',
    name: 'President of Armenia',
    aliases: ['ՀՀ նախագահ'],
    host: 'president.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['politics', 'regional'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'mfa-am',
    name: 'Ministry of Foreign Affairs and International Trade of Armenia',
    aliases: ['Ministry of Foreign Affairs of Armenia', 'ՀՀ արտաքին գործերի և միջազգային առևտրի նախարարություն', 'ՀՀ ԱԳՆ'],
    host: 'mfa.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['politics', 'security', 'regional'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'mil-am',
    name: 'Ministry of Defence of Armenia',
    aliases: ['ՀՀ ՊՆ'],
    host: 'mil.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['security', 'regional'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'cba-am',
    name: 'Central Bank of Armenia',
    aliases: ['ՀՀ Կենտրոնական բանկ'],
    host: 'cba.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['economy'],
    provenance: 'official-data',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'structured-adapter', readiness: 'planned' },
  },
  {
    id: 'armstat-am',
    name: 'Statistical Committee of Armenia',
    aliases: ['ՀՀ վիճակագրական կոմիտե', 'Armstat'],
    host: 'armstat.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['economy', 'society'],
    provenance: 'official-data',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'structured-adapter', readiness: 'planned' },
  },
  {
    id: 'mineconomy-am',
    name: 'Ministry of Economy of Armenia',
    aliases: ['ՀՀ էկոնոմիկայի նախարարություն'],
    host: 'mineconomy.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['economy', 'infrastructure', 'regional'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'minfin-am',
    name: 'Ministry of Finance of Armenia',
    aliases: ['ՀՀ ֆինանսների նախարարություն'],
    host: 'minfin.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['economy'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'mtad-am',
    name: 'Ministry of Territorial Administration and Infrastructure of Armenia',
    aliases: ['ՀՀ ՏԿԵՆ'],
    host: 'mtad.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['infrastructure', 'energy', 'economy'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'psrc-am',
    name: 'Public Services Regulatory Commission of Armenia',
    aliases: ['ՀՀ ՀԾԿՀ'],
    host: 'psrc.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['energy', 'infrastructure', 'economy'],
    provenance: 'official-data',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'structured-adapter', readiness: 'planned' },
  },
  {
    id: 'environment-am',
    name: 'Ministry of Environment of Armenia',
    aliases: ['ՀՀ շրջակա միջավայրի նախարարություն'],
    host: 'environment.gov.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['emergency', 'society', 'energy'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'rescue-am',
    name: 'Rescue Service of Armenia',
    aliases: ['ՀՀ փրկարար ծառայություն'],
    host: 'rescue.mia.gov.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy'],
    domains: ['emergency', 'infrastructure', 'society'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'ena-am',
    name: 'Electric Networks of Armenia',
    aliases: ['Հայաստանի էլեկտրական ցանցեր'],
    host: 'ena.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['energy', 'infrastructure'],
    provenance: 'sector-newsroom',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'structured-adapter', readiness: 'planned' },
  },
  {
    id: 'hightech-am',
    name: 'Ministry of High-Tech Industry and Artificial Intelligence of Armenia',
    aliases: ['ՀՀ բարձր տեխնոլոգիական արդյունաբերության և արհեստական բանականության նախարարություն'],
    host: 'hightech.gov.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['technology', 'economy', 'security', 'infrastructure'],
    provenance: 'official-primary',
    verificationPolicy: 'primary-record',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'eif-am',
    name: 'Enterprise Incubator Foundation',
    aliases: ['Ձեռնարկությունների Ինկուբատոր հիմնադրամ', 'EIF'],
    host: 'eif.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['technology', 'economy', 'society'],
    provenance: 'sector-newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'armenpress',
    name: 'Armenpress',
    host: 'armenpress.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['politics', 'economy', 'security', 'infrastructure', 'energy', 'society', 'technology', 'regional'],
    provenance: 'public-newswire',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'civilnet',
    name: 'CivilNet',
    host: 'civilnet.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['politics', 'economy', 'security', 'society', 'regional'],
    provenance: 'newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'hetq',
    name: 'Hetq',
    host: 'hetq.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'en'],
    domains: ['politics', 'economy', 'security', 'society', 'infrastructure'],
    provenance: 'newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'direct-rss', readiness: 'live', feedPath: '/hy/rss' },
  },
  {
    id: 'azatutyun',
    name: 'Azatutyun',
    host: 'azatutyun.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy'],
    domains: ['politics', 'security', 'society', 'regional'],
    provenance: 'newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'news-am',
    name: 'NEWS.am',
    host: 'news.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['politics', 'economy', 'security', 'society', 'regional'],
    provenance: 'newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'direct-rss', readiness: 'live', feedPath: '/hy/rss' },
  },
  {
    id: 'arka',
    name: 'ARKA',
    host: 'arka.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['economy', 'energy', 'regional'],
    provenance: 'sector-newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'banks-am',
    name: 'Banks.am',
    host: 'banks.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy'],
    domains: ['economy'],
    provenance: 'sector-newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'direct-rss', readiness: 'live', feedPath: '/am/rss/93' },
  },
  {
    id: 'panorama-am',
    name: 'Panorama.am',
    host: 'panorama.am',
    geography: 'armenia',
    countryCodes: ['AM'],
    languages: ['hy', 'ru', 'en'],
    domains: ['politics', 'economy', 'security', 'society', 'regional'],
    provenance: 'newsroom',
    verificationPolicy: 'corroborate-material-claim',
    collection: { strategy: 'google-news-site', readiness: 'live' },
  },
  {
    id: 'oc-media',
    name: 'OC Media',
    host: 'oc-media.org',
    geography: 'regional',
    countryCodes: ['AM', 'AZ', 'GE'],
    languages: ['en'],
    domains: ['politics', 'security', 'society', 'regional'],
    provenance: 'regional-newsroom',
    verificationPolicy: 'corroborate-before-alert',
    collection: { strategy: 'google-news-site', readiness: 'planned' },
  },
  {
    id: 'civil-ge',
    name: 'Civil.ge',
    host: 'civil.ge',
    geography: 'regional',
    countryCodes: ['GE'],
    languages: ['en'],
    domains: ['politics', 'security', 'economy', 'regional'],
    provenance: 'regional-newsroom',
    verificationPolicy: 'corroborate-before-alert',
    collection: { strategy: 'google-news-site', readiness: 'planned' },
  },
] as const;

export const ARMENIA_SOURCE_BY_ID: ReadonlyMap<string, ArmeniaSourceDefinition> = new Map(
  ARMENIA_SOURCE_REGISTRY.map((source) => [source.id, source]),
);

export function getArmeniaSourcesForDomain(domain: ArmeniaSignalDomain): ArmeniaSourceDefinition[] {
  return ARMENIA_SOURCE_REGISTRY.filter((source) => source.domains.includes(domain));
}

export function getArmeniaSourcesByReadiness(readiness: ArmeniaSourceReadiness): ArmeniaSourceDefinition[] {
  return ARMENIA_SOURCE_REGISTRY.filter((source) => source.collection.readiness === readiness);
}

export function getArmeniaSourceHomepage(source: ArmeniaSourceDefinition): string {
  const path = source.homepagePath ?? '/';
  return `https://${source.host}${path.startsWith('/') ? path : `/${path}`}`;
}

export function getArmeniaSourceFeedUrl(source: ArmeniaSourceDefinition): string | null {
  if (!source.collection.feedPath) return null;
  const path = source.collection.feedPath.startsWith('/') ? source.collection.feedPath : `/${source.collection.feedPath}`;
  return `https://${source.host}${path}`;
}
